version: '3.8'

services:
  pignews_db:
    container_name: pignews_db
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: djowdb
      POSTGRES_DB: pignews_db
    ports:
      - 5432:5432
  pignews_api:
    container_name: pignews_api
    restart: always
    depends_on:
      - pignews_db
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=pignews_db
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  postgres_volume:
